### ISSUE TITLE
WebUI: No response when clicking "Submit"

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/Registrator.jl#166]
Tested on Firefox and Chromium, Registrator latest master branch.

Ran with:
```julia
using Registrator
Registrator.WebUI.main()
```

With a `config.toml` in the same directory:
```toml
[web]
ip = "0.0.0.0"
port = 4000
server_url = "https://foo-bar.com"
disable_release_notes = true
registry_url = "https://gitlab.corporation.ca/corporation/PackageRegistry"
registry_clone_url = "https://oauth2:<token>@gitlab.corporation.ca/corporation/PackageRegistry"
registry_deps = ["https://github.com/JuliaRegistries/General"]
stop_file = "stopwebui"

[web.gitlab]
token = "<token>"
client_id = "<client id>"
client_secret = "<secret>"
api_url = "https://gitlab.corporation.ca/api/v4"
auth_url = "https://gitlab.corporation.ca/oauth/authorize"
token_url = "https://gitlab.corporation.ca/oauth/token"
disable_rate_limits = true
```

Git config contains only user name and email.
