### ISSUE TITLE
Failing to register new version of package using ssh address

### ISSUE THREAD

**Issue by racinmat** [JuliaRegistries/Registrator.jl#289]
Context: In our company we have private registry, and self-hosted registrator, and we use ssh keys for authentication for our self-hosted github.
Problem: I can not register new version of package when Registry is already using ssh address using the web UI.
In our registry, for packages we have e.g.
`Package.toml` in the registry
```toml
name = "InternalPackage"
uuid = "a2c437b0-bf6b-41a1-8a62-162a814afa99"
repo = "git@git.our_company.com:our_org/InternalPackage.jl.git"
```
when I put `git@git.our_company.com:our_org/InternalPackage.jl.git` to the form https://github.com/JuliaRegistries/Registrator.jl/blob/master/src/webui/templates/select.tpl
I obtain: ERROR: Package URL is invalid.

when I put `https://git.our_company.com:our_org/InternalPackage` to the form https://github.com/JuliaRegistries/Registrator.jl/blob/master/src/webui/templates/select.tpl
I obtain: ERROR: Registration failed: Changing package repo URL not allowed, please submit a pull request with the URL change to the target registry and retry.

Since we don't have anonymous clone allowed, we are using SSH keys everywhere and thus having https address would complicate things for us a lot.
