### ISSUE TITLE
Error: Julia version < 0.7 not allowed in [compat] despite correct version specification

### ISSUE THREAD

**Issue by cralibe** [JuliaRegistries/Registrator.jl#434]
Error while trying to register: "Julia version < 0.7 not allowed in [compat]"
```toml
[compat]
julia = ">= 1.6, < 2.0"
CSV = ">= 0.10, < 1.0"
Clustering = ">= 0.15, < 1.0"
Combinatorics = ">= 1.0, < 2.0"
DataFrames = ">= 1.0, < 2.0"
DataStructures = ">= 0.18, < 1.0"
Distances = ">= 0.10, < 1.0"
Distributions = ">= 0.24, < 1.0"
Documenter = ">= 1.6, < 2.0"
GaussianRandomFields = ">= 2.0, < 3.0"
Pipe = ">= 1.3, < 2.0"
Plots = ">= 1.40, < 2.0"
ProgressMeter = ">= 1.10, < 2.0"
SortingAlgorithms = ">= 1.1, < 2.0"
SpecialFunctions = ">= 1.0, < 3.0"
Statistics = "1"
StatsBase = ">= 0.33, < 1.0"
```

Steps I've Taken:
1. Verified that all dependencies in my Project.toml do not specify compatibility with Julia versions below 1.3.
2. Bumped the version number and tried re-registering.
3. Cleared the cache and re-ran my CI, which passes on Julia versions 1.6, 1.9, and nightly.

Additional Information:
1. CI setup tests on Julia 1.6, 1.9, and nightly.
2. The package works fine locally and in CI, but the registration process is blocked with the above error.
